name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests (Linux 4.11 support)
      run: cargo test --verbose
    - name: Run tests (Linux 4.14 support)
      run: cargo test --verbose --features linux4_14

    # Github does not have a 5.7+ kernel available yet, so we cannot execute
    # these tests, however we can make sure that the build works.
    # The LINUX_HEADERS environment variable is optional and points to headers
    # to use instead of the toolchain's system include path.
    - name: Build (Linux 5.7 support)
      run:
        sudo apt update &&
        sudo apt install -y linux-headers-5.8.0-49-generic &&
        export LINUX_HEADERS=/usr/src/linux-headers-5.8.0-49-generic &&
        cargo build --verbose --features linux5_7

    # As for 5.7, we cannot execute tests. Linux 5.11+ is not available at all
    # yet for Ubuntu 20.04, so we pull the headers from Ubuntu 21.04.
    - name: Build (Linux 5.11 support)
      run:
        echo 'deb http://cz.archive.ubuntu.com/ubuntu hirsute main' |
            sudo tee -a /etc/apt/sources.list &&
        sudo apt update &&
        sudo apt install -y linux-headers-5.11.0-16-generic &&
        export LINUX_HEADERS=/usr/src/linux-headers-5.11.0-16-generic &&
        cargo build --verbose

  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo Audit
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
